services:
  vue-frontend:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    volumes:
      - ./frontend:/app
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf 