services:
  # Backend Service (Django)
  web:
    build: ./backend/myproject
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend/myproject/:/usr/src/myproject/
    ports:
      - 8000:8000
    env_file:
      - ./backend/.env.dev
    depends_on:
      - db

  # PostgreSQL Database
  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/ # Persistent storage for PostgreSQL data
    environment:
      - POSTGRES_USER=hello_django
      - POSTGRES_PASSWORD=hello_django
      - POSTGRES_DB=hello_django_dev

  # Frontend Service (Vue)
  app:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: vue-app
    ports:
      - 8080:80
    depends_on:
      - web

  # Nginx for Frontend
  nginx_frontend:
    image: nginx:alpine
    container_name: nginx-app
    volumes:
      - ./frontend/nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
    depends_on:
      - app

volumes:
  postgres_data: # Named volume for persistent database storage
