services:
  web:
    build:
      context: ./myproject
      dockerfile: Dockerfile.prod
    # Run gunicorn on port 8000 
    command: gunicorn myproject.wsgi:application --bind 0.0.0.0$PORT
    volumes:
      - static_volume:/home/app/web/staticfiles
      - media_volume:/home/app/web/media
    expose:
      # Expose port 8000 for other container, I can't access in browser, nginx can 
      - 8000
    env_file:
      - ./.env.prod
    depends_on:
      - db
  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.prod.db
  nginx:
    build: ./nginx
    volumes:
      - static_volume:/home/app/web/staticfiles
      - media_volume:/home/app/web/media
    ports:
      - 8000:80
      # If i go to 127.0.0.1:8000 it goes to port 80 in container
      # 80 is being exposed to containers
    depends_on:
      - web

volumes:
  postgres_data:
  static_volume:
  media_volume:
