# Generated by Django 5.1.2 on 2024-10-26 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_api', '0004_review_feature_created_at_feature_is_active_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feature',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='feature',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='feature',
            name='updated_at',
        ),
    ]
