# Generated by Django 5.1.2 on 2024-11-04 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_api', '0008_category_created_at_category_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='plan',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ['-stars']},
        ),
    ]
