# Generated by Django 5.1.2 on 2024-11-05 10:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_api', '0010_flavour'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplement',
            name='flavour',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='flavour_supplement', to='main_api.flavour'),
            preserve_default=False,
        ),
    ]
