# Generated by Django 5.1.2 on 2024-11-05 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_api', '0012_size_alter_flavour_name_alter_supplement_flavour_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplement',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
