# Generated by Django 5.1.2 on 2024-10-26 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_api', '0005_remove_feature_created_at_remove_feature_is_active_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plan',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='plan',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='plan',
            name='updated_at',
        ),
    ]
