# Generated by Django 5.1.2 on 2024-11-05 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_api', '0014_alter_supplement_flavour'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supplement',
            name='flavour',
        ),
        migrations.RemoveField(
            model_name='supplement',
            name='size',
        ),
        migrations.AddField(
            model_name='supplement',
            name='flavour',
            field=models.ManyToManyField(related_name='flavour_supplements', to='main_api.flavour'),
        ),
        migrations.AddField(
            model_name='supplement',
            name='size',
            field=models.ManyToManyField(related_name='size_supplements', to='main_api.size'),
        ),
    ]
