# Generated by Django 5.1.2 on 2024-11-05 18:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_api', '0015_remove_supplement_flavour_remove_supplement_size_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='supplement',
            old_name='flavour',
            new_name='flavours',
        ),
        migrations.RenameField(
            model_name='supplement',
            old_name='size',
            new_name='sizes',
        ),
        migrations.RemoveField(
            model_name='supplement',
            name='price',
        ),
        migrations.CreateModel(
            name='SupplementPricing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('flavour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pricing_flavours', to='main_api.flavour')),
                ('size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pricing_sizes', to='main_api.size')),
                ('supplement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pricing', to='main_api.supplement')),
            ],
            options={
                'unique_together': {('supplement', 'flavour', 'size')},
            },
        ),
    ]
