# Generated by Django 5.1.2 on 2024-11-05 18:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_api', '0016_rename_flavour_supplement_flavours_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supplement',
            name='flavours',
        ),
        migrations.RemoveField(
            model_name='supplement',
            name='sizes',
        ),
        migrations.AddField(
            model_name='supplement',
            name='flavour',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='flavour_supplements', to='main_api.flavour'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='supplement',
            name='size',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='size_supplements', to='main_api.size'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='SupplementPricing',
        ),
    ]
