# Generated by Django 5.1.2 on 2024-11-05 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_api', '0017_remove_supplement_flavours_remove_supplement_sizes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplement',
            name='price',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=10),
            preserve_default=False,
        ),
    ]
