# Generated by Django 5.1.2 on 2024-11-13 13:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_api', '0019_remove_supplement_flavour_remove_supplement_size_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplement',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplements', to='main_api.category'),
        ),
    ]
